# Generated by Django 3.1.3 on 2020-12-21 02:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analityApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('PMO', 'PMO'), ('ANALISTA', 'ANALISTA'), ('GERENTE', 'GERENTE')], default='PMO', max_length=20)),
                ('permisos', models.CharField(choices=[('rw', 'Lectura y Escritura'), ('r', 'Lectura')], default=1, max_length=20)),
                ('pais', multiselectfield.db.fields.MultiSelectField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default=1, max_length=100)),
                ('formularios', multiselectfield.db.fields.MultiSelectField(choices=[('TODOS', 'TODOS'), ('Ans', 'Ans'), ('Volumetrias', 'Volumetrias'), ('HrsLabor', 'HrsLabor'), ('Ocupacion', 'Ocupacion'), ('Multas', 'Multas')], default='TODOS', max_length=200)),
                ('proyecto', models.ManyToManyField(to='analityApi.Proyectos')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
