# Generated by Django 3.1.3 on 2021-01-04 23:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='formularios',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TODOS', 'TODOS'), ('Ans', 'Ans'), ('Volumetrias', 'Volumetrias'), ('HrsLabor', 'HrsLabor'), ('Ocupacion', 'Ocupacion'), ('Multas', 'Multas')], default='Ocupacion', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='pais',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('PMO', 'PMO'), ('ANALISTA', 'ANALISTA'), ('GERENTE', 'GERENTE'), ('OCUPACION', 'OCUPACION')], default='OCUPACION', max_length=20),
        ),
    ]
