from django.urls import path, re_path, include
from analityApi import views 
 
urlpatterns = [
    path('api/proyectos', views.proyectos_list),
    path('api/proyectos_ocupacion', views.proyectos_list_ocupacion),
    path('api/pjs', views.pjs_list),
    path('api/periodos', views.periodos_list),
    path('api/serviciosAns', views.servicios_ans_list),
    path('api/serviciosVol', views.servicios_vol_list),
    path('api/serviciosHrsLabor', views.servicios_vol_list),
    path('api/multas', views.multas_list),
    path('api/ocupacion', views.ocupacion_list),
    path('api/hrs_labor', views.hrslabor_list),
    path('api/list_hrs_labor_new_month', views.hrslabor_list_new_month),
    path('api/hrs_labor_new_month', views.hrslabor_new_month),
    path('api/volumetrias', views.volumetrias_list),
    path('api/list_volumetrias_new_month', views.volumetrias_list_new_month),
    path('api/volumetrias_new_month', views.volumetrias_new_month),
    path('api/calculoVolumetria', views.calcular_volumetrias),
    path('api/ans', views.ans_list),
    path('api/list_ans_new_month', views.ans_list_new_month),
    path('api/ans_new_month', views.ans_new_month),
    path('api/get_users_ocupacion', views.get_user_rol),
    re_path(r'^api/servicios_ans/(?P<pk>[0-9]+)$', views.servicios_ans_detail),
    re_path(r'^api/servicios_vol/(?P<pk>[0-9]+)$', views.servicios_vol_detail),
    re_path(r'^api/servicios_hrs_labor/(?P<pk>[0-9]+)$', views.servicios_hrs_labor_detail),
    re_path(r'^api/multas/(?P<pk>[0-9]+)$', views.multas_detail),
    re_path(r'^api/ocupacion/(?P<pk>[0-9]+)$', views.ocupacion_detail),
    re_path(r'^api/hrs_labor/(?P<pk>[0-9]+)$', views.hrs_labor_detail),
    re_path(r'^api/volumetrias/(?P<pk>[0-9]+)$', views.volumetrias_detail),
    re_path(r'^api/ans/(?P<pk>[0-9]+)$', views.ans_detail),
    re_path(r'^app/.*$', views.index_vue),
]