# Generated by Django 3.1.3 on 2020-12-21 02:27

import analityApi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=20)),
                ('tipo_formato', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('indicadores_servicio', models.CharField(max_length=200)),
                ('nso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nso_dec', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ind_txt', models.CharField(blank=True, max_length=10, null=True)),
                ('obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('cumplimiento_general', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ans',
                'verbose_name_plural': 'Ans',
                'db_table': 'ans',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HrsLabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('linea_base_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('horas_ejecutadas', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uso', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Horas Labor',
                'verbose_name_plural': 'Horas Labor',
                'db_table': 'horas_labor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=20)),
                ('valor_facturacion', models.DecimalField(decimal_places=2, max_digits=12, validators=[analityApi.models.validate_cero])),
                ('porcentaje_multa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Multas',
                'db_table': 'multas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5')], default='S1', max_length=5)),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=20)),
                ('pm', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('linea_base_horas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('horas_ejecutadas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dedicacion', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Ocupacion',
                'verbose_name_plural': 'Ocupacion',
                'db_table': 'ocupacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20, unique=True)),
                ('trm_co', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trm_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trm_gt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trm_hn', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trm_ni', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('trm_sv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pjs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj', models.CharField(max_length=30)),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=100)),
                ('ebc', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pjs',
                'verbose_name_plural': 'Pjs',
                'db_table': 'pjs',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=100)),
                ('formulario_ocupacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Volumetrias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=20)),
                ('servicio', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('registrados', models.IntegerField(blank=True, null=True)),
                ('cerrados', models.IntegerField(blank=True, null=True)),
                ('backlog', models.IntegerField(blank=True, null=True)),
                ('backlog_y_registrados', models.IntegerField(blank=True, null=True)),
                ('eficiencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.periodos', to_field='periodo')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos')),
            ],
            options={
                'verbose_name': 'Volumetrias',
                'verbose_name_plural': 'Volumetrias',
                'db_table': 'volumetrias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=100)),
                ('servicio', models.CharField(max_length=250)),
                ('indicadores_servicio', models.CharField(blank=True, max_length=250, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicios',
                'db_table': '',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='proyectos',
            constraint=models.UniqueConstraint(fields=('proyecto', 'pais'), name='unique_proyecto_pais'),
        ),
        migrations.AddConstraint(
            model_name='pjs',
            constraint=models.UniqueConstraint(fields=('pj', 'pais'), name='unique_pj'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.periodos', to_field='periodo'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='pj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.pjs'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos'),
        ),
        migrations.AddField(
            model_name='multas',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.periodos', to_field='periodo'),
        ),
        migrations.AddField(
            model_name='multas',
            name='pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.pjs'),
        ),
        migrations.AddField(
            model_name='multas',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos'),
        ),
        migrations.AddField(
            model_name='hrslabor',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.periodos', to_field='periodo'),
        ),
        migrations.AddField(
            model_name='hrslabor',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos'),
        ),
        migrations.AddField(
            model_name='ans',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.periodos', to_field='periodo'),
        ),
        migrations.AddField(
            model_name='ans',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos'),
        ),
    ]
