# Generated by Django 3.1.3 on 2020-12-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analityApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicios',
            table='servicios',
        ),
    ]
