# Generated by Django 3.1.3 on 2021-01-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analityApi', '0002_auto_20201221_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'ordering': ['id'], 'verbose_name': 'Ocupación PMO y BackOffice', 'verbose_name_plural': 'Ocupación PMO y BackOffice'},
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
