# Generated by Django 3.1.3 on 2021-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analityApi', '0006_auto_20210120_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='nso',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='ans',
            name='nso_dec',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
