# Generated by Django 3.1.3 on 2021-01-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analityApi', '0007_auto_20210120_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosHrsLabor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('COLOMBIA', 'COLOMBIA'), ('COSTA RICA', 'COSTA RICA'), ('GUATEMALA', 'GUATEMALA'), ('HONDURAS', 'HONDURAS'), ('NICARAGUA', 'NICARAGUA'), ('EL SALVADOR', 'EL SALVADOR')], default='COLOMBIA', max_length=100)),
                ('servicio', models.CharField(max_length=250)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analityApi.proyectos')),
            ],
            options={
                'verbose_name': 'Servicios Horas Labor',
                'verbose_name_plural': 'Servicios Horas Labor',
                'db_table': 'servicios_hrsLabor',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
