# Generated by Django 3.1.3 on 2021-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analityApi', '0008_servicioshrslabor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupacion',
            name='horas_ejecutadas',
        ),
        migrations.RemoveField(
            model_name='ocupacion',
            name='linea_base_horas',
        ),
        migrations.RemoveField(
            model_name='ocupacion',
            name='semana',
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='observaciones',
            field=models.CharField(default='', max_length=255),
        ),
    ]
